addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.5.5")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.20.1")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.5.12")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.4.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.4.0")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"                 % "0.13.2")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"                       % "2.3.1")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"               % "3.6.3")
